### PR TITLE
enable github actions build using platformio

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ping @sleemanj

**Comment by thijstriemstra** [comment]
this should use github actions instead of travis.

**Comment by thijstriemstra** [comment]
@sleemanj can you enable github actions for this repository?

**Comment by sleemanj** [comment]
I don't know anything about all this, but the settings seem to indicate that "Allow all actions" is already enabled.

**Comment by thijstriemstra** [comment]
weird, because this page doesn't show any builds (for me): https://github.com/sleemanj/JQ6500_Serial/pull/27/checks

Maybe it'll get triggered once this is (squash) merged to master? If there are any CI failures there, I'll take a look then.

**Comment by sleemanj** [comment]
No idea sorry, I don't know anything about Actions or what you are wanting to happen.  I'm just an old-school coder.

I'd assume you should enable the actions in your fork since your pull reqiests have not yet been merged.

**Comment by thijstriemstra** [comment]
ah yeah of course. It ran successfully on my fork: https://github.com/thijstriemstra/JQ6500_Serial/runs/2727152111

Should be good to go @sleemanj 

> No idea sorry, I don't know anything about Actions or what you are wanting to happen. 

This service provided by github basically compiles the library everytime a new commit is made to master. Any incompatibilities with boards we test against will be visible.

**Comment by lucadentella** [comment]
Hi! If you prefer to stay with "plain" Arduino, an "official" github action is available too:
https://github.com/arduino/arduino-cli

I normally use it in my repos to test sketches/libraries before accepting PRs.

**Comment by thijstriemstra** [comment]
or even better, run both

**Comment by thijstriemstra** [comment]
@sleemanj any decision on this PR?

**Comment by sleemanj** [comment]
I dont' know anything about it, but it doesn't change the code so I guess it can do no harm.  Merged.

**Comment by thijstriemstra** [comment]
thanks, looks good so far:

https://github.com/sleemanj/JQ6500_Serial/actions/runs/3131965659

**Pull request merged**
